# Stellar Network Configuration
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
HORIZON_URL = "https://horizon.stellar.org"

# Account information
ACCOUNTS = ["GAAAAAABBBBBBBBBCCCCCCCCDDDDDDDDDDDDDDD"]

# Additional Metadata
[asset]
CODE = "BTC"
ISSUER = "G... (Issuer Account)"
LOGO_URL = "https://example.com/logo.png"
